### ISSUE TITLE
When watching a long video to the end and seek back - things go wrong

### ISSUE THREAD

**Issue by guypaskar** [gpac/mp4box.js#42]
Here is the scenario.

Play a long (i took a 15 minutes video)video to the end then seek back to the half of the video.

The sourceBuffer (of the video) buffered has only one range in it - [midSecOfVideo,endSecOfVideo] - possibly it is being dropped by the video tag so it won't take too much memory.

Now , when calling MP4Box.prototype.seek seekInfo gets the right seek_info.offset
But this.inputIsoFile.findEndContiguousBuf returns the offset of the end of the video - So , It does not return the needed offset...

**Comment by guypaskar** [comment]
has anyone else experienced that?

**Comment by hanzeil** [comment]
I also found this problem

**Comment by cconcolato** [comment]
Thanks for the report. Indeed, I confirm the bug in the demo app. I would need to return from a seek call additional information to indicate if data fetch is needed or not. The pb is that in the current demo app, the download drives the whole processing. I would need to change that. Needs more thoughts.

**Comment by guypaskar** [comment]
The question is, Is the date gone at some point and need to be downloaded again? (say that cache is disabled...)
It looks to me that indeed the data is gone and needs to be downloaded again, right?
I would be happy to think about it with you.

**Comment by cconcolato** [comment]
There are 2 levels of buffering: 
- at the player level (i.e. internally in the browser), that's what you see in the player UI (the light grey part) and what you get when you call ```HTMLMediaElement.buffered```. Here it is a buffer of frames.
- at MP4box.js level, here it is a buffer of bytes (the bytes passed via appendBuffer). I need to document how to control when the data in this buffer is released.

**Comment by guypaskar** [comment]
So , after discussing it with cyril , it seems to me that the best option is to keep the buffers of mp4box and the buffers of the video tag synced when video tag is evacuating data.

This , when mp4box is always synced with what's in the video tag buffer , the value returning from seek and appendBuffers that indicates what's the next download position should be will be correct.

@rbouqueau what do you think about that?

**Comment by guypaskar** [comment]
@cconcolato any news on that?

**Comment by cconcolato** [comment]
I've pushed a lot of commits, with a heavy restructuring of the code and new features. My testing shows that your issue is solved. Can you check?

**Comment by guypaskar** [comment]
Actually , things now does not work for me (regardless of this bug) 

Still trying to understand why, but it seems like appends are not consistently happening. (i.e same series of downloads results in differents behaviour on the player. again, I'm still not sure what's happening.
Are there any changes required to the main file (the file that handles the player/mp4box calls) in the new code?

**Comment by cconcolato** [comment]
I had to make many changes in the buffer management. This might have introduced bugs. Can you produce a log so that I check? Can you also check that the demo app works? 

Regarding the changes in the main app, calling mp4box.start() is now required.
.

**Comment by guypaskar** [comment]
Yes I saw that. Where is the right place to put mp4box.start() ?

I will try to produce the logs when I'll understand more about what the issue is...

**Comment by cconcolato** [comment]
```start``` tells mp4box to start providing segments to the application. It should be called after the initialization segments are received, and after a ```seek```.

**Comment by guypaskar** [comment]
I don't see that you use it after seek in the demo page...

**Comment by cconcolato** [comment]
Should be better written but it's there:
```
	downloader.setChunkStart(mp4box.seek(0, true).offset);
	downloader.setChunkSize(parseInt(chunkSizeLabel.value));
	downloader.setInterval(parseInt(chunkTimeoutLabel.value));
	downloader.resume();
	mp4box.start();
```

**Comment by guypaskar** [comment]
I meant there is one after initialization segments are received but not after seeks etc.

**Comment by cconcolato** [comment]
I see, I was confusing. It should not be needed after a seek.

**Comment by publicocean0** [comment]
For me it is ok. I tested it in a 15mins video with seek back , loop . It is ok :)

**Comment by cconcolato** [comment]
Seems to be resolved. Closing. Reopen if this is not the case.
